# version: 3

services:

  angular:
    build: .
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - dist:/app/dist/browser
    container_name: nodejs-app
    command: npm run watch

  web-server:
    image: nginx:stable-alpine3.20
    ports:
      - 4200:80
    volumes:
      - dist:/usr/share/nginx/html:ro

    
volumes:
  dist: